### PR TITLE
fix(1282): StudentTraceView - add redirection on trace delete

### LINKED ISSUE #1282: [Bug]: [FE] Détail d'une trace - Pas de redirection après suppression de la trace
### Bug Summary

Détail d'une trace - Pas de redirection après suppression de la trace

### Steps to Reproduce

1. Aller sur le détail d'une trace
2. La supprimer

### Expected Behavior

Redirection vers la bibliothèque de trace

### Actual Behavior

Aucune redirection

### Stacktrace

_No response_

### Related Epic

Epic : #5

### Environment

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by p-beger**
### Brief description of changes applied
This PR adds a redirection in the StudentTraceView when a trace is deleted, improving navigation and user experience. Now, after deleting a trace, the user is redirected appropriately.

**Main changes:**
- 🐛 Adds redirection logic on trace delete in StudentTraceView.vue
- ✅ Updates and adds tests for navigation and redirection
- ➕ Updates use-navigation composable for new logic

---

### Reference to an Issue, Feature, Task, User Story or another PR
Closes https://github.com/avenirs-esr/AVENIRS-Project/issues/1282

---

### Documentation
- Updated `StudentTraceView.vue` and `use-navigation.ts` to handle redirection after trace deletion.
- Added and updated related test files.

**Modified files:**
- `src/features/student/traces/views/StudentTraceView/StudentTraceView.vue`
- `src/common/composables/use-navigation/use-navigation.ts`
- `src/common/composables/use-navigation/use-navigation.test.ts`

---

### Target Branch
`develop`

---

### Additional Notes
This change ensures users are redirected after deleting a trace, preventing confusion and improving flow.

---

### Known Limitations or Side Effects
No known limitations or side effects.

---

## ✅ Checklist

- [ ] a11y tested (if the PR includes frontend changes)
- [ ] Tests provided (including unit and integration tests for both frontend and backend)
- [ ] i18n handled (texts are translated)
- [ ] Performance tests
- [ ] No unnecessary code (e.g., debug logs, commented code)
- [ ] Code style and formatting rules respected (linting, conventions, etc.)
- [ ] Semantic Versioning respected
- [ ] Add to `CHANGELOG.md` file all properties and database change and details for the update process

### CODE REVIEW

File: src/common/composables/use-navigation/use-navigation.ts [hunk 1]
```diff
@@ -97,7 +97,11 @@ export function useNavigation () {
     return router.push(to)
   }
 
-  const navigateToStudentTraces = () => {
+  const navigateToStudentTraces = ({ replace }: { replace?: boolean } = { replace: false }) => {
```
Comment (elrhourha) [inline src/common/composables/use-navigation/use-navigation.ts:111]: pas beosin d'un object vu qu'on a un seul arg

**Review by elrhourha — CHANGES_REQUESTED** [review]

File: src/common/composables/use-navigation/use-navigation.ts (hunk 1 above)
Comment (p-beger) [reply src/common/composables/use-navigation/use-navigation.ts:111]: Ils sont tous fait comme ça @elrhourha, c'est par souci d'uniformité

Comment (p-beger) [reply src/common/composables/use-navigation/use-navigation.ts:111]: Et quand bien même @elrhourha , le fait d'avoir un objet est plus parlant que juste un arg

**Review by elrhourha — APPROVED** [review]
