### PR TITLE
fix(1016): error message component implementation

### LINKED ISSUE #1016: [FRONT] Implémentation du composant ResourceNotFoundMessage dans les différentes features
## Epic lié

[🔗 AVENIRS-Project #302](https://github.com/orgs/avenirs-esr/projects/18/views/1?pane=issue&itemId=115434471&issue=avenirs-esr%7CAVENIRS-Project%7C302)

### Origine ou cause :
Suite à l'intégration du composant `ResourceNotFoundMessage`

### Propositions de refactoring ou amélioration :
Prendre exemple sur l'implémentation qui a été faite dans `StudentSkillView` (lien de la PR : https://github.com/avenirs-esr/avenirs-cofolio-client/pull/359).
Il faut repasser sur toutes les views faisant appel à une ressource au niveau du back (en général ayant un param `:id` dans leur route côté front) et implémenter le nouveau composable `useApiErrors` et gérer l'affichage avec le composant `ResourceNotFoundMessage`.

- Issue liée : #302

### PR DESCRIPTION
**Pull request by Nathan-Pignon**
🚨 **Reminder:** This template is not meant to be submitted as part of the pull request body.  
Please use it as a guide, and replace or remove it before creating your PR.

Thanks again for your work! 💪

# Read Before Submissions

Thank you for your contributions to CoFolio.

When you publish the pull request, please check off relevant items below in the description of your pull request.

---

### Brief description of changes applied

---

### Reference to an Issue, Feature, Task, User Story or another PR

Closes https://github.com/avenirs-esr/AVENIRS-Project/issues/1016

---

### Documentation

---

### Target Branch

---

### Additional Notes

---

### Known Limitations or Side Effects

---

## ✅ Checklist

Please make sure you have addressed the following before submitting:

- [ ] a11y tested (if the PR includes frontend changes)
- [ ] Tests provided (including unit and integration tests for both frontend and backend)
- [ ] i18n handled (texts are translated)
- [ ] Performance tests
- [ ] No unnecessary code (e.g., debug logs, commented code)
- [ ] Code style and formatting rules respected (linting, conventions, etc.)
- [ ] Semantic Versioning respected
- [ ] Add to `CHANGELOG.md` file all properties and database change and detaiils for the update process

---

# Remember

**DO NOT** keep this template as is when you submit. Please remove or adjust the description when you submit your pull request.

Please do not submit a pull request to ask questions.

Do not submit pull requests without tests that verify or reproduce your intended use case. The pull request will
most likely be automatically closed immediately, unless the change is extremely trivial.

### CODE REVIEW

File: src/features/student/personalCareer/views/DeclaredProgramDetailedView/DeclaredProgramDetailedView.vue [hunk 1]
```diff
@@ -43,24 +48,33 @@ function handleConfirmDelete () {
...
+  <Loader
+    :is-loading="isLoading && !isError"
+    size="2xl"
+  >
+    <div
+      v-if="declaredProgramDetailed"
+      class="av-row av-gap-2xl"
     >
+      <div class="av-col">
+        <DeclaredProgramSideMenu
```
Comment (elrhourha) [inline src/features/student/personalCareer/views/DeclaredProgramDetailedView/DeclaredProgramDetailedView.vue]: @Nathan-Pignon c'est voulu le fait de wrap DeclaredProgramSideMenu dans Loader .?

Comment (Nathan-Pignon) [reply src/features/student/personalCareer/views/DeclaredProgramDetailedView/DeclaredProgramDetailedView.vue]: Oui c'était pour ne pas avoir un rendu bizarre et avoir le loader en attendant que tout soit chargé avant d'afficher. Mais après réflexion c'est vrai que ça pourrait être utile de pouvoir utiliser la navigation pendant le chargement. Il faut juste revoir l'affichage mais je vais regarder ça

**Review by elrhourha — APPROVED** [review]
