### PR TITLE
fix(1418): add theme for button on delete overlay

### LINKED ISSUE #1418: [Bug]: Bouton de suppression de la même couleur que la card
### Bug Summary

Le bouton de suppression d'une association en cours (dans la modale d'association) est de la même couleur que la card, ce qui fait qu'elle n'est visible seulement lorsque l'on passe dessus.

### Steps to Reproduce

Se rendre sur le détail d'une trace
Cliquer sur l'onglet "Mes éléments associés"
Cliquer sur le dropdown "Associer..." puis sur "Une/des compétence(s)"
Cliquer dans le champs de recherche d'une compétence déclarée
Sélectionner une ou plusieurs compétence(s)

### Expected Behavior

Les cards s'affichent sur le côté avec un fond bleu et une croix est visible en haut à droite de chacune d'entre elles

### Actual Behavior

Les cards s'affichent sur le côté avec un fond bleu et la croix est invisible car elle est de la même couleur, elle est visible seulement lorsqu'on l'on passe dessus avec la souris

### Stacktrace

_No response_

### Related Epic

Epic : #5

### Environment

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Nathan-Pignon**
🚨 **Reminder:** This template is not meant to be submitted as part of the pull request body.  
Please use it as a guide, and replace or remove it before creating your PR.

Thanks again for your work! 💪

# Read Before Submissions

Thank you for your contributions to CoFolio.

When you publish the pull request, please check off relevant items below in the description of your pull request.

---

### Brief description of changes applied

---

### Reference to an Issue, Feature, Task, User Story or another PR

Closes https://github.com/avenirs-esr/AVENIRS-Project/issues/1418

---

### Documentation

---

### Target Branch

---

### Additional Notes

---

### Known Limitations or Side Effects

---

## ✅ Checklist

Please make sure you have addressed the following before submitting:

- [ ] a11y tested (if the PR includes frontend changes)
- [ ] Tests provided (including unit and integration tests for both frontend and backend)
- [ ] i18n handled (texts are translated)
- [ ] Performance tests
- [ ] No unnecessary code (e.g., debug logs, commented code)
- [ ] Code style and formatting rules respected (linting, conventions, etc.)
- [ ] Semantic Versioning respected
- [ ] Add to `CHANGELOG.md` file all properties and database change and detaiils for the update process

---

# Remember

**DO NOT** keep this template as is when you submit. Please remove or adjust the description when you submit your pull request.

Please do not submit a pull request to ask questions.

Do not submit pull requests without tests that verify or reproduce your intended use case. The pull request will
most likely be automatically closed immediately, unless the change is extremely trivial.

### CODE REVIEW

File: src/features/student/global/components/interaction/DeleteOverlay/DeleteOverlay.vue [hunk 1]
```diff
@@ -1,9 +1,10 @@
 <script setup lang="ts">
-import { AvButton, MDI_ICONS } from '@avenirs-esr/avenirs-dsav'
+import { AvButton, type AvButtonProps, MDI_ICONS } from '@avenirs-esr/avenirs-dsav'
 import { useI18n } from 'vue-i18n'
 
 export interface DeleteOverlayProps {
   buttonLabel?: string
+  theme?: AvButtonProps['theme']
```
Comment (p-beger) [inline src/features/student/global/components/interaction/DeleteOverlay/DeleteOverlay.vue]: Pourquoi ne pas l'appeler buttonTheme ici aussi pour que ce soit plu parlant ? En plus juste au dessus tu as "buttonLabel"

**Review by p-beger — CHANGES_REQUESTED** [review]
Un peu de pinaillage ;)

**Review by p-beger — APPROVED** [review]
C'est bon pour moi, merci Nathan !
