### PR TITLE
fix(1030): include new features in demo mode

### LINKED ISSUE #1030: [FRONT] Désactiver le mode démo sur les nouvelles features
### Description
Désactiver le mode démon sur le lien `Construire mon projet de vie --> Mon parcours` pour pouvoir accéder aux formations et compétences déclarées

### PR DESCRIPTION
**Pull request by Nathan-Pignon**
🚨 **Reminder:** This template is not meant to be submitted as part of the pull request body.  
Please use it as a guide, and replace or remove it before creating your PR.

Thanks again for your work! 💪

# Read Before Submissions

Thank you for your contributions to CoFolio.

When you publish the pull request, please check off relevant items below in the description of your pull request.

---

### Brief description of changes applied

---

### Reference to an Issue, Feature, Task, User Story or another PR

Closes https://github.com/avenirs-esr/AVENIRS-Project/issues/1030

---

### Documentation

---

### Target Branch

---

### Additional Notes

---

### Known Limitations or Side Effects

---

## ✅ Checklist

Please make sure you have addressed the following before submitting:

- [ ] a11y tested (if the PR includes frontend changes)
- [ ] Tests provided (including unit and integration tests for both frontend and backend)
- [ ] i18n handled (texts are translated)
- [ ] Performance tests
- [ ] No unnecessary code (e.g., debug logs, commented code)
- [ ] Code style and formatting rules respected (linting, conventions, etc.)
- [ ] Semantic Versioning respected
- [ ] Add to `CHANGELOG.md` file all properties and database change and detaiils for the update process

---

# Remember

**DO NOT** keep this template as is when you submit. Please remove or adjust the description when you submit your pull request.

Please do not submit a pull request to ask questions.

Do not submit pull requests without tests that verify or reproduce your intended use case. The pull request will
most likely be automatically closed immediately, unless the change is extremely trivial.

### CODE REVIEW

File: src/features/student/personalCareer/views/PersonalCareerView/layouts/PersonalCareerLayout/PersonalCareerLayout.vue [hunk 1]
```diff
@@ -33,6 +33,19 @@ const items = computed<AvSideNavigationItem[]>(() => [
...
+    id: ROUTES.STUDENT.PERSONAL_CAREER_DECLARED_PROGRAMS.name,
+    label: t('student.personalCareer.views.PersonalCareerView.ProgramsSection.title'),
+    icon: MDI_ICONS.SCHOOL_OUTLINE
+  },
+  {
+    id: ROUTES.STUDENT.PERSONAL_CAREER_EXPERIENCES.name,
+    label: t('student.personalCareer.views.PersonalCareerView.ExperiencesSection.title'),
+    icon: MDI_ICONS.VECTOR_POLYGON_VARIANT
+  }
+])
```
Comment (p-beger) [inline src/features/student/personalCareer/views/PersonalCareerView/layouts/PersonalCareerLayout/PersonalCareerLayout.vue]: Pourquoi répéter les items plutôt que les rendre conditionnels dans le tableau de base ?

File: src/features/student/personalCareer/views/PersonalCareerView/layouts/PersonalCareerLayout/PersonalCareerLayout.vue [hunk 2]
```diff
@@ -43,7 +56,7 @@ function navigateToSelectedItem (routeName: string) {
     <AvSideNavigation
       v-model:is-side-menu-collapsed="isSideMenuCollapsed"
       :selected-item="selectedItem"
-      :items="items"
+      :items="isDemoMode ? demoItems : items"
```
Comment (p-beger) [inline src/features/student/personalCareer/views/PersonalCareerView/layouts/PersonalCareerLayout/PersonalCareerLayout.vue]: Comme ça ici tu passes toujours juste ton items

File: src/features/student/personalCareer/views/PersonalCareerView/sections/ExperiencesSection/components/DeclaredExperiencesMoreActionsDropdown/DeclaredExperiencesMoreActionsDropdown.vue [hunk 3]
```diff
@@ -33,6 +35,19 @@ const menuItems = computed<AvDropdownItem[]>(() => [
...
+    icon: MDI_ICONS.PLUS_CIRCLE_OUTLINE,
+    label: t('student.personalCareer.views.PersonalCareerView.ExperiencesSection.DeclaredExperiencesMoreActionsDropdown.add')
+  },
+  {
+    name: DeclaredExperiencesMoreActionsDropdownEvents.DELETE,
+    icon: MDI_ICONS.TRASH_CAN_OUTLINE,
+    label: t('student.personalCareer.views.PersonalCareerView.ExperiencesSection.DeclaredExperiencesMoreActionsDropdown.delete')
+  },
+])
+
```
Comment (p-beger) [inline src/features/student/personalCareer/views/PersonalCareerView/sections/ExperiencesSection/components/DeclaredExperiencesMoreActionsDropdown/DeclaredExperiencesMoreActionsDropdown.vue]: Idem ici, ça duplique le code alors que tu pourrais juste rendre conditionnel dans ton tableau comme t'as déjà fait sur des devs précédents

File: src/features/student/personalCareer/views/PersonalCareerView/sections/ProgramsSection/components/DeclaredProgramsMoreActionsDropdown/DeclaredProgramsMoreActionsDropdown.vue [hunk 4]
```diff
@@ -33,8 +35,21 @@ const menuItems = computed<AvDropdownItem[]>(() => {
...
+      icon: MDI_ICONS.PLUS_CIRCLE_OUTLINE,
+      label: t('student.personalCareer.views.PersonalCareerView.ProgramsSection.DeclaredProgramsMoreActionsDropdown.add')
+    },
+    {
+      name: ProgramsMoreActionsDropdownEvents.DELETE,
+      icon: MDI_ICONS.TRASH_CAN_OUTLINE,
+      label: t('student.personalCareer.views.PersonalCareerView.ProgramsSection.DeclaredProgramsMoreActionsDropdown.delete')
+    },
+  ]
 })
```
Comment (p-beger) [inline src/features/student/personalCareer/views/PersonalCareerView/sections/ProgramsSection/components/DeclaredProgramsMoreActionsDropdown/DeclaredProgramsMoreActionsDropdown.vue]: Idem c'est dupliqué, faut le rendre conditionnel dans le tableau de base

**Review by p-beger — CHANGES_REQUESTED** [review]

**Review by p-beger — DISMISSED** [review]
Nickel pour moi, merci Nathan !

**Review by p-beger — APPROVED** [review]
