### PR TITLE
fix(1185): add button to access on activity detailed

### LINKED ISSUE #1185: [FE] Ajouter le bouton pour accéder au detail d'une activité si inscrit
### Description
Il manque le bouton pour accéder au détail d'une activité si l'étudiant est inscrit

### PR DESCRIPTION
**Pull request by Nathan-Pignon**
🚨 **Reminder:** This template is not meant to be submitted as part of the pull request body.  
Please use it as a guide, and replace or remove it before creating your PR.

Thanks again for your work! 💪

# Read Before Submissions

Thank you for your contributions to CoFolio.

When you publish the pull request, please check off relevant items below in the description of your pull request.

---

### Brief description of changes applied

---

### Reference to an Issue, Feature, Task, User Story or another PR

Closes https://github.com/avenirs-esr/AVENIRS-Project/issues/1185

---

### Documentation

---

### Target Branch

---

### Additional Notes

---

### Known Limitations or Side Effects

---

## ✅ Checklist

Please make sure you have addressed the following before submitting:

- [ ] a11y tested (if the PR includes frontend changes)
- [ ] Tests provided (including unit and integration tests for both frontend and backend)
- [ ] i18n handled (texts are translated)
- [ ] Performance tests
- [ ] No unnecessary code (e.g., debug logs, commented code)
- [ ] Code style and formatting rules respected (linting, conventions, etc.)
- [ ] Semantic Versioning respected
- [ ] Add to `CHANGELOG.md` file all properties and database change and detaiils for the update process

---

# Remember

**DO NOT** keep this template as is when you submit. Please remove or adjust the description when you submit your pull request.

Please do not submit a pull request to ask questions.

Do not submit pull requests without tests that verify or reproduce your intended use case. The pull request will
most likely be automatically closed immediately, unless the change is extremely trivial.

### CODE REVIEW

File: src/features/student/buildProject/views/ProjectActivitiesCatalogView/components/ActivityPreview/ActivityPreview.vue [hunk 1]
```diff
@@ -15,8 +17,17 @@ export interface ActivityPreviewProps {
 defineProps<ActivityPreviewProps>()
 
 const { t } = useI18n()
+const router = useRouter()
 const { showModal: showUnsubscribeModal, displayModal: displayUnsubscribeModal, hideModal: hideUnsubscribeModal } = useModal()
 const { showModal: showSubscribeModal, displayModal: displaySubscribeModal, hideModal: hideSubscribeModal } = useModal()
+
+function navigateToActivityDetailed ({ id, thematic }: { id?: string, thematic?: string }) {
```
Comment (elrhourha) [inline src/features/student/buildProject/views/ProjectActivitiesCatalogView/components/ActivityPreview/ActivityPreview.vue]: @Nathan-Pignon on a le fichier @src/common/composables/use-navigation/use-navigation.ts dans lequel on centralise les fonctions de navigation

**Review by elrhourha — CHANGES_REQUESTED** [review]

File: src/features/student/buildProject/locales/en.json [hunk 2]
```diff
@@ -14,6 +14,7 @@
           }
         },
         "buttons": {
+          "access": "Access my activity",
```
Comment (elrhourha) [inline src/features/student/buildProject/locales/en.json]: @Nathan-Pignon `buttons` contient les trads utilisé dans plusieurs view, ton button est utilisé que dans `ActivityPreview`

**Review by elrhourha — CHANGES_REQUESTED** [review]

**Review by elrhourha — APPROVED** [review]
