### PR TITLE
fix(1295): DeclaredProgramDetailedView - use QuerySuspense

### LINKED ISSUE #1295: [Bug]: [FE] Message d'erreur affiché au mauvais endroit sur la page de détail de formation déclarée
### Bug Summary

Message d'erreur affiché au mauvais endroit sur la page de détail de formation déclarée

### Steps to Reproduce

/cofolio/student/project/personal-career/declared-programs/87b29aa9-b6f7-48ea-bcfb-305e88e1ae62

### Expected Behavior

Affichage propre soit au dessus soit en dessous du contenu

### Actual Behavior

Affichage entre la side nav et le contenu

### Stacktrace

_No response_

### Related Epic

Epic : #574

### Environment

_No response_

### Screenshots

Image

### PR DESCRIPTION
**Pull request by p-beger**
### Brief description of changes applied
This PR refactors the declared program detail loading/error handling by replacing direct  +  usage with the shared  component, and adds support for custom error descriptions in .

**Main changes:**
- ♻️ Refactors  to use 
- ✨ Adds  prop support to 
- ✅ Updates stubs and unit tests to align with  behavior
- 📝 Updates  documentation with the new prop
- 🐛 Improves control of error message wording/position in declared program detail view

---

### Reference to an Issue, Feature, Task, User Story or another PR
Closes https://github.com/avenirs-esr/AVENIRS-Project/issues/1295

---

### Documentation
Updated files include:
- 
- 
- 
- 
- 

---

### Target Branch

---

### Additional Notes
For not-found business errors, the view now passes explicit localized title and description through  props. For generic API errors, it still falls back to API-provided message content.

---

### Known Limitations or Side Effects
No known side effects identified.

---

## ✅ Checklist

Please make sure you have addressed the following before submitting:

- [ ] a11y tested (if the PR includes frontend changes)
- [ ] Tests provided (including unit and integration tests for both frontend and backend)
- [ ] i18n handled (texts are translated)
- [ ] Performance tests
- [ ] No unnecessary code (e.g., debug logs, commented code)
- [ ] Code style and formatting rules respected (linting, conventions, etc.)
- [ ] Semantic Versioning respected
- [ ] Add to  file all properties and database change and details for the update process

### CODE REVIEW

**Review by Nathan-Pignon — DISMISSED** [review]
Ok pour moi, merci Pascal !

**Review by elrhourha — DISMISSED** [review]
Merci @p-beger

File: src/features/student/personalCareer/views/DeclaredProgramDetailedView/DeclaredProgramDetailedView.vue [hunk 1]
```diff
@@ -64,20 +63,13 @@ function handleConfirmDelete () {
         @load-more-programs="loadMoreDeclaredPrograms"
       />
     </div>
-    <Loader
+    <QuerySuspense
+      :error="error"
       :is-loading="isLoading && !isError"
-      size="2xl"
+      :is-empty="!declaredProgramDetailed"
```
Comment (elrhourha) [inline src/features/student/personalCareer/views/DeclaredProgramDetailedView/DeclaredProgramDetailedView.vue]: @p-beger vu que c'est une ressource par id tu peux ignorer le isEmpty, c'est soit la ressource existe soit 404 erro

**Review by elrhourha — APPROVED** [review]
