### PR TITLE
fix(1279): Activity detailed view - add redirection to unsubscribed event

### LINKED ISSUE #1279: [Bug]: [FE] Détail d'une activité - Désinscription - pas de redirection
### Bug Summary

Détail d'une activité - Désinscription - pas de redirection 

### Steps to Reproduce

1. Aller sur le détail d'une activité
2. Déplier le dropdown
3. Sélectionner se désinscrire et valider 

### Expected Behavior

Désinscription OK -> redirection OK

### Actual Behavior

Désinscription KO -> pas de redirection

### Stacktrace

_No response_

### Related Epic

Epic : #6

### Environment

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by p-beger**
### Brief description of changes applied
This PR adds a redirection to the unsubscribed event in the Activity detailed view. If a user tries to access an activity they are not subscribed to, they are now redirected appropriately, improving navigation and user experience.

**Main changes:**
- ✨ Adds redirection logic for unsubscribed events in ProjectActivityDetailedView.vue
- ✅ Adds and updates tests for navigation and redirection
- ➕ Updates use-navigation composable for new logic

---

### Reference to an Issue, Feature, Task, User Story or another PR
Closes https://github.com/avenirs-esr/AVENIRS-Project/issues/1279

---

### Documentation
- Updated `ProjectActivityDetailedView.vue` and `use-navigation.ts` to handle redirection for unsubscribed events.
- Added and updated related test files.

**Modified files:**
- `src/features/student/buildProject/views/ProjectActivityDetailedView/ProjectActivityDetailedView.vue`
- `src/features/student/buildProject/views/ProjectActivityDetailedView/ProjectActivityDetailedView.test.ts`
- `src/common/composables/use-navigation/use-navigation.ts`
- `src/common/composables/use-navigation/use-navigation.test.ts`

---

### Target Branch
`develop`

---

### Additional Notes
This change ensures users are redirected if they attempt to access activities they are not subscribed to, preventing confusion and improving flow.

---

### Known Limitations or Side Effects
No known limitations or side effects.

---

## ✅ Checklist

- [ ] a11y tested (if the PR includes frontend changes)
- [ ] Tests provided (including unit and integration tests for both frontend and backend)
- [ ] i18n handled (texts are translated)
- [ ] Performance tests
- [ ] No unnecessary code (e.g., debug logs, commented code)
- [ ] Code style and formatting rules respected (linting, conventions, etc.)
- [ ] Semantic Versioning respected
- [ ] Add to `CHANGELOG.md` file all properties and database change and details for the update process

### CODE REVIEW

File: src/common/composables/use-navigation/use-navigation.ts [hunk 1]
```diff
@@ -97,6 +97,17 @@ export function useNavigation () {
     return router.push(to)
   }
 
+  const navigateToStudentProjectActivities = ({ replace }: { replace?: boolean } =
```
Comment (elrhourha) [inline src/common/composables/use-navigation/use-navigation.ts:100]: pas besoin d'un object en tant que param vu qu'on a pas plus de 3 args

**Review by elrhourha — CHANGES_REQUESTED** [review]

File: src/common/composables/use-navigation/use-navigation.ts (hunk 1 above)
Comment (p-beger) [reply src/common/composables/use-navigation/use-navigation.ts:100]: Ils sont tous fait comme ça @elrhourha, c'est par souci d'uniformité

Comment (p-beger) [reply src/common/composables/use-navigation/use-navigation.ts:100]: Et quand bien même @elrhourha , le fait d'avoir un objet est plus parlant que juste un arg

**Review by elrhourha — APPROVED** [review]
