### PR TITLE
fix(1117): add e2e tests for access activity details button

### LINKED ISSUE #1117: [TEST] Implémenter les tests E2E et vérifier que l'US #1027 est complètement fonctionnelle sur dev
### Description

- [ ] ⚠️ Implémenter les tests E2E
- [ ] Vérifier que l'US https://github.com/avenirs-esr/AVENIRS-Project/issues/10127 est complètement fonctionnelle selon les RG

### PR DESCRIPTION
**Pull request by Nathan-Pignon**
🚨 **Reminder:** This template is not meant to be submitted as part of the pull request body.  
Please use it as a guide, and replace or remove it before creating your PR.

Thanks again for your work! 💪

# Read Before Submissions

Thank you for your contributions to CoFolio.

When you publish the pull request, please check off relevant items below in the description of your pull request.

---

### Brief description of changes applied

---

### Reference to an Issue, Feature, Task, User Story or another PR

Closes https://github.com/avenirs-esr/AVENIRS-Project/issues/1117

---

### Documentation

---

### Target Branch

---

### Additional Notes

---

### Known Limitations or Side Effects

---

## ✅ Checklist

Please make sure you have addressed the following before submitting:

- [ ] a11y tested (if the PR includes frontend changes)
- [ ] Tests provided (including unit and integration tests for both frontend and backend)
- [ ] i18n handled (texts are translated)
- [ ] Performance tests
- [ ] No unnecessary code (e.g., debug logs, commented code)
- [ ] Code style and formatting rules respected (linting, conventions, etc.)
- [ ] Semantic Versioning respected
- [ ] Add to `CHANGELOG.md` file all properties and database change and detaiils for the update process

---

# Remember

**DO NOT** keep this template as is when you submit. Please remove or adjust the description when you submit your pull request.

Please do not submit a pull request to ask questions.

Do not submit pull requests without tests that verify or reproduce your intended use case. The pull request will
most likely be automatically closed immediately, unless the change is extremely trivial.

### CODE REVIEW

File: e2e/framework/student/lifeProject/activitiesCatalog/componentObjects/ActivityPreview.ts [hunk 1]
```diff
@@ -100,6 +104,22 @@ export class ActivityPreview extends BaseObject {
...
   }
 
+  async verifyAccessButtonVisible () {
+    const expectedText = t('student.buildProject.activities.views.ProjectActivitiesCatalogView.buttons.access')
+    await expect(this.getAccessButton()).toBeVisible()
+    await expect(this.getAccessButton()).toHaveText(expectedText)
+  }
+
+  async verifyAccessButtonHidden () {
+    await expect(this.getAccessButton()).toHaveCount(0)
```
Comment (elrhourha) [inline e2e/framework/student/lifeProject/activitiesCatalog/componentObjects/ActivityPreview.ts]:
```suggestion
    await expect(this.getAccessButton()).isHidden()
```

**Review by elrhourha — CHANGES_REQUESTED** [review]

**Review by elrhourha — APPROVED** [review]
