### PR TITLE
fix(1275): SelfKnowledge - remove share actions from demo mode

### LINKED ISSUE #1275: [Bug]: [FE] Dropdowns catégories et élément "Me connaître" : présence de fonctionnalités non implémentées (ici partager)
### Bug Summary

Dropdowns catégories et élément "Me connaître" : présence de fonctionnalités non implémentées (ici partager)

### Steps to Reproduce

Bug 1 : Aller sur la page des catégories, cliquer sur le dropdown

Bug 2 : Aller sur le détail d'un élément d'une catégorie, cliquer sur le dropdown

### Expected Behavior

Uniquement présence d'actions implémentées

### Actual Behavior

Présences d'actions non implémentées :
- Bug 1 : Partager mes éléments
- Bug 2 : Partager

### Stacktrace

_No response_

### Related Epic

Epic : #38

### Environment

_No response_

### Screenshots

Bug 1 :

Image

Bug 2 :

Image

### PR DESCRIPTION
**Pull request by p-beger**
### Brief description of changes applied
This PR removes share actions from the SelfKnowledge feature in demo mode. This ensures that demo users do not see or interact with sharing functionality, providing a more accurate demo experience.

**Main changes:**
- 🐛 Removes share actions from SelfKnowledgeElementsDropdown.vue and SelfKnowledgeElementDetailsDropdown.vue in demo mode

---

### Reference to an Issue, Feature, Task, User Story or another PR
Closes https://github.com/avenirs-esr/AVENIRS-Project/issues/1275

---

### Documentation
- Updated `SelfKnowledgeElementsDropdown.vue` and `SelfKnowledgeElementDetailsDropdown.vue` to conditionally hide share actions in demo mode.
- No changes to public documentation required.

**Modified files:**
- `src/features/student/selfKnowledge/views/SelfKnowledgeCategoryView/components/SelfKnowledgeElementsDropdown/SelfKnowledgeElementsDropdown.vue`
- `src/features/student/selfKnowledge/views/SelfKnowledgeCategoryView/components/SelfKnowledgeElementDetailsDropdown/SelfKnowledgeElementDetailsDropdown.vue`

---

### Target Branch
`develop`

---

### Additional Notes
This change ensures that demo users only see features available in the demo, improving clarity and user experience.

---

### Known Limitations or Side Effects
No known limitations or side effects.

---

## ✅ Checklist

- [ ] a11y tested (if the PR includes frontend changes)
- [ ] Tests provided (including unit and integration tests for both frontend and backend)
- [ ] i18n handled (texts are translated)
- [ ] Performance tests
- [ ] No unnecessary code (e.g., debug logs, commented code)
- [ ] Code style and formatting rules respected (linting, conventions, etc.)
- [ ] Semantic Versioning respected
- [ ] Add to `CHANGELOG.md` file all properties and database change and details for the update process

### CODE REVIEW

File: src/features/student/selfKnowledge/views/SelfKnowledgeCategoryView/components/SelfKnowledgeElementDetailsDropdown/SelfKnowledgeElementDetailsDropdown.vue [hunk 1]
```diff
@@ -16,23 +16,32 @@ enum SelfKnowledgeElementDetailsDropdownEvents {
...
-    label: t('global.buttons.delete')
-  },
-  {
-    name: SelfKnowledgeElementDetailsDropdownEvents.SHARE,
-    icon: MDI_ICONS.SHARE_VARIANT_OUTLINE,
-    label: t('global.buttons.share')
+const isDemo = false
+
+const menuItems = computed<AvDropdownItem[]>(() => {
+  const items = [
```
Comment (elrhourha) [inline src/features/student/selfKnowledge/views/SelfKnowledgeCategoryView/components/SelfKnowledgeElementDetailsDropdown/SelfKnowledgeElementDetailsDropdown.vue]: @p-beger tu peux le faire bia des spread c'est plus elegant que push

**Review by elrhourha — CHANGES_REQUESTED** [review]

File: src/features/student/selfKnowledge/views/SelfKnowledgeCategoryView/components/SelfKnowledgeElementDetailsDropdown/SelfKnowledgeElementDetailsDropdown.vue (hunk 1 above)
Comment (p-beger) [reply src/features/student/selfKnowledge/views/SelfKnowledgeCategoryView/components/SelfKnowledgeElementDetailsDropdown/SelfKnowledgeElementDetailsDropdown.vue]: C'est fait @elrhourha :+1:

**Review by elrhourha — APPROVED** [review]
