### PR TITLE
fix(672): remove trace addition date information

### LINKED ISSUE #672: detail d'une trace - date d'ajout en double
### Description

la date d'ajout est en double, ne garder uniquement celle du haut

### Éléments UI de travail

Image

### PR DESCRIPTION
**Pull request by Nathan-Pignon**
🚨 **Reminder:** This template is not meant to be submitted as part of the pull request body.  
Please use it as a guide, and replace or remove it before creating your PR.

Thanks again for your work! 💪

# Read Before Submissions

Thank you for your contributions to CoFolio.

When you publish the pull request, please check off relevant items below in the description of your pull request.

---

## 📝 Pull Request Description

---

Fixes https://github.com/avenirs-esr/AVENIRS-Project/issues/672
---

---

---

---

---

## ✅ Checklist

Please make sure you have addressed the following before submitting:

- [ ] a11y tested (if the PR includes frontend changes)
- [ ] Tests provided (including unit and integration tests for both frontend and backend)
- [ ] i18n handled (texts are translated)
- [ ] Performance tests
- [ ] No unnecessary code (e.g., debug logs, commented code)
- [ ] Code style and formatting rules respected (linting, conventions, etc.)
- [ ] Semantic Versioning respected
- [ ] Add to `CHANGELOG.md` file all properties and database change and detaiils for the update process

---

# Remember

**DO NOT** keep this template as is when you submit. Please remove or adjust the description when you submit your pull request.

Please do not submit a pull request to ask questions.

Do not submit pull requests without tests that verify or reproduce your intended use case. The pull request will
most likely be automatically closed immediately, unless the change is extremely trivial.

### CODE REVIEW

File: src/features/student/views/StudentToolsTracesView/components/StudentTraceDetails/StudentTraceDetails.vue [hunk 1]
```diff
@@ -54,13 +53,6 @@ const traceAttachmentFile = computed(() => {
               :valid-message="t('global.success.file.loaded')"
               disabled
             />
-            <div class="student-detailed-trace-information__file-info">
-              <div class="b2-light student-detailed-trace-information__upload-date">
-                {{
-                  t('student.views.studentToolsTracesView.studentTraceDetails.addedOn', { date: formattedTraceCreationDate })
```
Comment (p-beger) [inline src/features/student/views/StudentToolsTracesView/components/StudentTraceDetails/StudentTraceDetails.vue:60]: T'as pas supprimé les traductions associées, il y en a besoin ailleurs ?

Comment (Nathan-Pignon) [reply src/features/student/views/StudentToolsTracesView/components/StudentTraceDetails/StudentTraceDetails.vue:60]: Oui il est utilisé ailleurs

**Review by p-beger — DISMISSED** [review]
C'est ok pour moi, merci Nathan !

**Review by p-beger — APPROVED** [review]
